### ISSUE TITLE
[Windows] Server console freezes when a resource is stopped

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-js-module-v2#161] opened 2024-01-10 04:40 UTC
On Windows only, the server console freezes at ``Stop resource [resource name]`` when a resource stops (when a resource is restarted or the server is stopped). 

This doesn't happen all the time, although it does happen frequently, but randomly.

**Comment by Yiin** [comment] 2024-02-19 01:37
Added more logging when resource is being stopped, post log when the issue re-occurs, thanks.

**Comment by xLuxy** [comment] 2024-02-19 09:34
Note: It will be available in `dev/0.0.0-dev.22`+ - a build should come later this day once the other issues are fixed :)

**Comment by xxshady** [comment] 2024-02-20 01:30
> Added more logging when resource is being stopped, post log when the issue re-occurs, thanks.

do you mean these?

```
[04:30:04] [JS] Stopping resource jsv2-native-vector3
[04:30:04] [JS] Emitting process exit event
[04:30:04] [JS] Resetting asyncResource
[04:30:04] [JS] Emitting process exit event
[04:30:04] [JS] Stopping environment
[04:30:04] [JS] Freeing environment
[04:30:04] [JS] Freeing isolate data
[04:30:04] [JS] Closing uv loop
[04:30:04] [JS] Resetting resource
[04:30:04] [JS] Cleaning up metrics
[04:30:04] [JS] Resource stopped
```

It just doesn't log anything when it occurs

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/bea2c846-26cc-4ae8-ad3e-94dbb8e5fe35)

**Comment by Yiin** [comment] 2024-02-20 03:49
@xxshady thanks, so it appears to be happening because sometimes the promise that is calling ON_EVENT doesn't resolve.

You can see that using these logs

```diff
diff --git a/shared/src/Event.cpp b/shared/src/Event.cpp
index 6c6b745..6385a5d 100644
--- a/shared/src/Event.cpp
+++ b/shared/src/Event.cpp
@@ -30,7 +30,11 @@ void js::Event::SendEvent(const alt::CEvent* ev, IResource* resource)
     js::Promise promise = CallEventBinding(false, (int)ev->GetType(), eventArgs, resource);
     eventArgs.Get()->SetAlignedPointerInInternalField(1, nullptr);
     if(!promise.IsValid()) return;
-    if(ev->GetType() == alt::CEvent::Type::RESOURCE_STOP && static_cast<const alt::CResourceStopEvent*>(ev)->GetResource() == resource->GetResource()) promise.Await();
+    if(ev->GetType() == alt::CEvent::Type::RESOURCE_STOP && static_cast<const alt::CResourceStopEvent*>(ev)->GetResource() == resource->GetResource()) {
+        js::Logger::Info("Awaiting promise", promise.IsValid(), promise.HasResolver());
+        promise.Await();
+        js::Logger::Info("Promise resolved");
+    }
 }
```

![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/aa210c2f-7c54-411f-a294-7065c802950a)

**Comment by xLuxy** [comment] 2024-02-21 18:52
Issue has been fixed in https://github.com/altmp/altv-js-module-v2/commit/1370065e948287b54ce4833a9691b16b38982300 - feel free to re-open when it still happens.

**Comment by xxshady** [comment] 2024-03-04 16:26
and i don't know how to reproduce it

**Comment by xxshady** [comment] 2024-03-04 16:27
reproduced it

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/da5286a6-b368-4a89-a153-a40ebe7fd5d5)

**Comment by xLuxy** [comment] 2024-09-16 09:34
Fixed in https://github.com/altmp/altv-js-module-v2/commit/0aeec1077e9e3bb6f5c71fa03b310fcb548a15f0

**Closed by xLuxy** 2024-09-16 09:34 UTC
Labels: scope: shared, scope: question
